name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt pyinstaller

      - name: Build executable
        run: |
          pyinstaller Altomatic.spec

      - name: Package build output
        run: |
          $distDir = Join-Path (Get-Location) "dist"
          $appDir = Join-Path $distDir "Altomatic"
          if (-not (Test-Path $appDir)) {
            Write-Error "Build output directory not found: $appDir"
            exit 1
          }
          Compress-Archive -Path "$appDir\*" -DestinationPath "Altomatic-${{ github.ref_name }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Altomatic-${{ github.ref_name }}
          path: Altomatic-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Altomatic-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
